name: 'slash-schema-validation'
description: 'Validate JSON, YAML, XML against a schema'
author: 'cardinalby'
inputs:
  schema:
    description: 'Schema file path or URL'
    required: false
  file:
    description: '| separated files to validate. Globs are allowed'
    required: true
outputs:
  errorType:
    description: '`file` or `schema` or `validation`'
  validation_error:
    description: 'Error during file validation'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'code'
